"""empty message

Revision ID: df197834a5ef
Revises: 
Create Date: 2024-03-31 13:54:36.817908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df197834a5ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('bname', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memb_name', sa.String(length=50), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('ord_name', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderss')
    op.drop_table('member')
    op.drop_table('blog')
    # ### end Alembic commands ###
