"""tell changes

Revision ID: f640e4daa417
Revises: 864fe3e55e24
Create Date: 2024-03-31 19:58:48.033713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f640e4daa417'
down_revision = '864fe3e55e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('content')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ord_name', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('blog_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'blog', ['blog_id'], ['bid'])
        batch_op.drop_column('oname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oname', sa.VARCHAR(length=70), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('blog_id')
        batch_op.drop_column('ord_name')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
